import Link from "next/link";
import AuthButton from "@/components/AuthButton";

export const metadata = {
  title: "Terms of Service — Clueboard",
};

const LAST_UPDATED = "May 10, 2026";

export default function TermsPage() {
  return (
    <main className="flex-1 flex flex-col">
      <header className="px-4 sm:px-6 py-4 flex items-center justify-between border-b border-white/10">
        <Link href="/" className="font-serif text-xl font-black text-gold-bright">
          Clueboard
        </Link>
        <div className="flex items-center gap-4">
          <Link href="/play" className="text-sm text-white/70 hover:text-white">
            Play today &rarr;
          </Link>
          <AuthButton next="/play" />
        </div>
      </header>

      <article className="flex-1 px-4 sm:px-6 py-10 max-w-2xl mx-auto w-full">
        <h1 className="font-serif text-4xl font-black text-gold-bright mb-2">
          Terms of Service
        </h1>
        <p className="text-white/50 text-sm mb-8">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-6 text-white/85 leading-relaxed">
          <p>
            By using Clueboard at clueboard.app (the &ldquo;Service&rdquo;), you agree to these Terms. The short version: have fun, don&rsquo;t cheat or abuse the site, the Service is provided as-is, and we&rsquo;re a small independent project, not Jeopardy!.
          </p>

          <Section title="Eligibility">
            <p>
              You must be at least 13 years old to use Clueboard.
            </p>
          </Section>

          <Section title="Your account">
            <p>
              You can play anonymously. If you sign in with Google, you&rsquo;re responsible for keeping access to your Google account secure. We don&rsquo;t handle your password directly &mdash; that&rsquo;s between you and Google.
            </p>
            <p>
              You may delete your Clueboard account at any time by emailing us (see the Privacy Policy).
            </p>
          </Section>

          <Section title="Acceptable use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Attempt to access another user&rsquo;s account or data.</li>
              <li>Probe, scan, or test the vulnerability of the Service without prior written permission.</li>
              <li>Submit automated traffic, scrapers, or bots that disrupt normal play.</li>
              <li>Reverse-engineer or copy the Service in a way that infringes our rights.</li>
              <li>Use the Service to transmit malicious code or harassing content.</li>
            </ul>
          </Section>

          <Section title="Trivia content">
            <p>
              Clue text on Clueboard is original work generated by AI (Claude, by Anthropic) using public, freely-licensed trivia datasets &mdash; including the{" "}
              <a className="underline" target="_blank" rel="noreferrer" href="https://opentdb.com">Open Trivia Database</a> (CC BY-SA 4.0) and{" "}
              <a className="underline" target="_blank" rel="noreferrer" href="https://the-trivia-api.com">The Trivia API</a> (CC BY 4.0). Underlying facts are not copyrightable; the rewritten clue text is original to Clueboard.
            </p>
            <p>
              Clueboard is an independent project. It is <strong>not</strong> affiliated with, endorsed by, or sponsored by Sony Pictures Television, Jeopardy Productions, Inc., or any television show. &ldquo;Jeopardy!&rdquo; and related marks are the property of their respective owners.
            </p>
          </Section>

          <Section title="Our intellectual property">
            <p>
              The Clueboard name, design, code, and clue text are owned by us and made available for personal, non-commercial use. You may not copy, redistribute, or create competing derivative services from our content without permission.
            </p>
          </Section>

          <Section title="Service changes">
            <p>
              We may modify, suspend, or discontinue any part of the Service at any time, with or without notice. We may also change these Terms; the &ldquo;Last updated&rdquo; date will reflect any change, and material changes will be flagged in the app.
            </p>
          </Section>

          <Section title="Disclaimer of warranties">
            <p>
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties of any kind, express or implied. We do not guarantee that clues are factually correct, that the Service will be uninterrupted, or that it will meet your expectations. Trivia clues may contain errors despite our efforts; use at your own risk.
            </p>
          </Section>

          <Section title="Limitation of liability">
            <p>
              To the maximum extent permitted by law, Clueboard and its operators are not liable for any indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the Service. Our total liability for any claim relating to the Service is limited to the greater of $50 USD or the amount you paid us in the past 12 months (which, on our free service, is zero).
            </p>
          </Section>

          <Section title="Termination">
            <p>
              We may suspend or terminate access for any user who violates these Terms or whose use of the Service threatens its operation. You may stop using the Service and delete your account at any time.
            </p>
          </Section>

          <Section title="Governing law">
            <p>
              These Terms are governed by the laws of the United States and the state in which the Service operator resides, without regard to conflict-of-law rules. Any dispute will be resolved in the courts of that jurisdiction.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about these Terms? Email{" "}
              <a className="underline" href="mailto:jeremy.laliberty3@gmail.com">jeremy.laliberty3@gmail.com</a>.
            </p>
          </Section>

          <p className="text-xs text-white/40 italic mt-12">
            These Terms are written in plain language for clarity; they are not legal advice. If you operate Clueboard commercially, you should have a lawyer review and tailor them to your situation.
          </p>
        </div>
      </article>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-serif text-xl font-black text-gold-bright mb-2">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}
